name: Build OpenWRT with zroxy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2


      - name: Clone OpenWRT repo
        run: |
          rm -rf openwrt
          [ -f openwrt-sdk-21.02.7-mvebu-cortexa53_gcc-8.4.0_musl.Linux-x86_64.tar.xz ] || wget http://downloads.openwrt.org/releases/21.02.7/targets/mvebu/cortexa53/openwrt-sdk-21.02.7-mvebu-cortexa53_gcc-8.4.0_musl.Linux-x86_64.tar.xz
          [ -d openwrt-sdk-21.02.7-mvebu-cortexa53_gcc-8.4.0_musl.Linux-x86_64 ] || tar -xf openwrt-sdk-21.02.7-mvebu-cortexa53_gcc-8.4.0_musl.Linux-x86_64.tar.xz
          cd openwrt-sdk-21.02.7-mvebu-cortexa53_gcc-8.4.0_musl.Linux-x86_64
          #ls openwrt-sdk-21.02.7-mvebu-cortexa53_gcc-8.4.0_musl*
          #ls staging_dir/*


      - name: Clone zroxy repository
        run: |
          cd openwrt-sdk-21.02.7-mvebu-cortexa53_gcc-8.4.0_musl.Linux-x86_64/
          git clone https://github.com/0x7a657573/zroxy.git

      - name: Automate Configure OpenWRT
        run: |
          openwrt_architecture_host=aarch64-openwrt-linux-musl
          cd openwrt-sdk-21.02.7-mvebu-cortexa53_gcc-8.4.0_musl.Linux-x86_64/zroxy
 

      - name: Compile OpenWRT with zroxy package
        run: | 
          
          
          openwrt_architecture_host=aarch64-openwrt-linux-musl
          cd openwrt-sdk-21.02.7-mvebu-cortexa53_gcc-8.4.0_musl.Linux-x86_64/
          
          openwrt_sdk_folder=$(pwd)
          openwrt_toolchain=toolchain-aarch64_cortex-a53_gcc-8.4.0_musl
          PATH="$PATH:$openwrt_sdk_folder/staging_dir/$openwrt_toolchain/bin/"
          export PATH
          
          STAGING_DIR="$openwrt_sdk_folder/staging_dir/$openwrt_toolchain/"
          export STAGING_DIR
          
          cd zroxy
          
          export CC="aarch64-openwrt-linux-musl-gcc -static -Os" 
          cmake .
          
          #[ -f ./configure ]&&./configure  --host=$openwrt_architecture_host --enable-static
          
          make CC=aarch64-openwrt-linux-musl-gcc LD=aarch64-openwrt-linux-musl-ld 
          aarch64-openwrt-linux-musl-strip zroxy
          ls *

      - name: Upload compiled zroxy firmware
        uses: actions/upload-artifact@v4
        with:
          name: zroxy
          path: openwrt-sdk-21.02.7-mvebu-cortexa53_gcc-8.4.0_musl.Linux-x86_64/zroxy/zroxy
