name: Build OpenWRT with zroxy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up OpenWRT build environment
        run: |
          sudo apt update
          sudo apt install -y build-essential libncurses5-dev gawk zlib1g-dev asciidoc binutils

      - name: Clone OpenWRT repo
        run: |
          git clone https://git.openwrt.org/openwrt/openwrt.git
          cd openwrt
          git branch -a
          git tag
          git checkout v21.02.3
          #./scripts/feeds update -a
          #./scripts/feeds install -a

      - name: Clone zroxy repository
        run: |
          cd openwrt/package
          git clone https://github.com/0x7a657573/zroxy.git

      - name: Automate Configure OpenWRT
        run: |
          cd openwrt
          # make menuconfig
          grep zroxy .config
          # For example, enabling zroxy package via configuration
          sed -i 's/^#CONFIG_PACKAGE_zroxy=y/CONFIG_PACKAGE_zroxy=y/' .config
          grep zroxy .config

      - name: Compile OpenWRT with zroxy package
        run: |
          cd openwrt
          make package/zroxy/{clean,compile}  V=s

      - name: Upload compiled zroxy firmware
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-firmware
          path: openwrt/bin/
